### ISSUE TITLE
Liaison des comptes réseaux sociaux au compte utilisateur

### ISSUE THREAD

**Issue by Antoine2lop** [McRecrut/dash#7]
**Système de liaison du compte discord aux compte site** 

Le système de liaison comprend l’envoi de différent champ en base de données

Les informations demandées sont : 

- ` user_id` (int)
- ` social_id` (varchar 100)
- ` social_username` (varchar 140)
- ` type` (text)

Informations complémentaires : 

- ` id` (int)

Les actions d'ajout de compte au profil et de suppression son log avec l'api de log en base de données

Taches pour la finalisation du système : 

- [x] Création des boutons d'ajout et de suppression de la liaison sur le dashboard
- [x] Ajout des logs d'ajout et de suppression
- [x] Enregistrement du pseudo discord et de l'id en base de données

Liaison avec les différent réseau sociaux : 

- [x] Discord
- [x] Twitter
- [x] Github

**Comment by CapybaraPin** [comment]
Liaison des reseaux sociaux ✅ 
+ Système d'activité
